DIRS = LDMM/LDMMAtlas \
	LDMM/LDMMWarp \
	LDMM/LDMMShootingAtlas \
	LDMM/LDMMShootingWarp \
	LDMM/LDMMAdShootingWarp \
	Greedy/AtlasWerks \
	Greedy/GreedyAtlas \
	Greedy/GreedyWarp \
	Metamorphosis/MetamorphosisAverageMultiscale \
	Metamorphosis/MetamorphosisMultiscale

clean:
	-for d in $(DIRS); do (cd $$d; $(MAKE) clean ); done
